name: pytest Test

on:
  push:
    paths:
      - 'mrubis_controller/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install mypy
      - name: Test with pytest
        run: python -m pytest
        working-directory: .
